# -*- coding: utf-8 -*-
"""ML_Project_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fY3LNpSCHoq4ZqZuIN1AcKVehgPgxdSn
"""

import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/ML-Project-01/Tweets.csv')

print(df.shape)

df.head()

df.info()

df['airline_sentiment'].value_counts()

df['airline'].value_counts()
